name: TempApp
options:
  bundleIdPrefix: kz.temp
  deploymentTarget:
    iOS: '15.0'

targets:
  TempApp:
    type: application
    platform: iOS
    sources:
      - TempApp
    resources:
      - TempApp/LaunchScreen.storyboard
      - TempApp/Assets.xcassets

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: kz.temp.app
        PRODUCT_NAME: TEMP
        TARGETED_DEVICE_FAMILY: '1'
        SUPPORTS_MACCATALYST: NO
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen

    info:
      path: TempApp/Info.plist
      properties:
        CFBundleDisplayName: ТЕМП
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: '4.0'
        CFBundleVersion: '4'
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
