name: TempApp
options:
  bundleIdPrefix: kz.temp
  deploymentTarget:
    iOS: '15.0'
targets:
  TempApp:
    type: application
    platform: iOS
    sources:
      - TempApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: kz.temp.app
        PRODUCT_NAME: TEMP
        TARGETED_DEVICE_FAMILY: '1'
        SUPPORTS_MACCATALYST: NO
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: TempApp/Info.plist
